package tacos.openapi;

import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import reactor.core.publisher.Mono;

// Ejercicio 35: Versionar la API y publicar contrato OpenAPI
@Controller
@CrossOrigin(origins = "*")
public class SwaggerUiController {

  private static final String SWAGGER_HTML = "<!DOCTYPE html>\n"
      + "<html lang=\"es\">\n"
      + "<head>\n"
      + "  <meta charset=\"UTF-8\">\n"
      + "  <title>Taco Cloud API - Swagger UI & OpenAPI Contract</title>\n"
      + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
      + "  <style>\n"
      + "    :root {\n"
      + "      --primary: #d35400;\n"
      + "      --primary-dark: #a04000;\n"
      + "      --bg: #f8f9fa;\n"
      + "      --text: #2c3e50;\n"
      + "      --card-bg: #ffffff;\n"
      + "      --border: #e2e8f0;\n"
      + "      --get: #61affe;\n"
      + "      --post: #49cc90;\n"
      + "      --patch: #50e3c2;\n"
      + "      --delete: #f93e3e;\n"
      + "    }\n"
      + "    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; background: var(--bg); color: var(--text); line-height: 1.6; }\n"
      + "    header { background: #1e293b; color: white; padding: 1.5rem 2rem; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }\n"
      + "    .brand { display: flex; align-items: center; gap: 0.75rem; font-size: 1.5rem; font-weight: 700; }\n"
      + "    .brand span { color: var(--primary); }\n"
      + "    .nav-links a { color: #cbd5e1; text-decoration: none; margin-left: 1.25rem; font-size: 0.95rem; transition: color 0.2s; }\n"
      + "    .nav-links a:hover { color: white; }\n"
      + "    .container { max-width: 1200px; margin: 2rem auto; padding: 0 1.5rem; }\n"
      + "    .hero-card { background: var(--card-bg); border-radius: 12px; padding: 2rem; margin-bottom: 2rem; border: 1px solid var(--border); box-shadow: 0 2px 4px rgba(0,0,0,0.02); }\n"
      + "    .badge { display: inline-block; padding: 0.35rem 0.65rem; border-radius: 6px; font-size: 0.8rem; font-weight: 600; text-transform: uppercase; }\n"
      + "    .badge-v1 { background: #e0f2fe; color: #0369a1; }\n"
      + "    .badge-v2 { background: #dcfce7; color: #15803d; }\n"
      + "    .version-selector { margin-top: 1rem; display: flex; gap: 1rem; align-items: center; }\n"
      + "    select { padding: 0.5rem 1rem; border-radius: 6px; border: 1px solid var(--border); font-size: 1rem; background: white; }\n"
      + "    .endpoint-card { background: white; border-radius: 8px; margin-bottom: 0.75rem; border: 1px solid var(--border); overflow: hidden; transition: box-shadow 0.2s; }\n"
      + "    .endpoint-card:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.05); }\n"
      + "    .endpoint-header { display: flex; align-items: center; padding: 1rem 1.25rem; gap: 1rem; font-family: monospace; font-size: 0.95rem; }\n"
      + "    .method { padding: 0.25rem 0.6rem; border-radius: 4px; font-weight: 700; color: white; min-width: 60px; text-align: center; }\n"
      + "    .method.get { background: var(--get); }\n"
      + "    .method.post { background: var(--post); }\n"
      + "    .method.patch { background: var(--patch); color: #0f172a; }\n"
      + "    .method.delete { background: var(--delete); }\n"
      + "    .path { font-weight: 600; color: #0f172a; flex: 1; }\n"
      + "    .summary { color: #64748b; font-family: -apple-system, sans-serif; font-size: 0.9rem; }\n"
      + "    .btn { display: inline-block; padding: 0.5rem 1rem; border-radius: 6px; background: var(--primary); color: white; text-decoration: none; font-weight: 600; transition: background 0.2s; }\n"
      + "    .btn:hover { background: var(--primary-dark); }\n"
      + "    .btn-secondary { background: #e2e8f0; color: #334155; margin-left: 0.5rem; }\n"
      + "    .btn-secondary:hover { background: #cbd5e1; }\n"
      + "  </style>\n"
      + "</head>\n"
      + "<body>\n"
      + "  <header>\n"
      + "    <div class=\"brand\">🌮 Taco Cloud <span>OpenAPI Contract</span></div>\n"
      + "    <nav class=\"nav-links\">\n"
      + "      <a href=\"/v3/api-docs\" target=\"_blank\">📄 JSON OAS 3.0</a>\n"
      + "      <a href=\"/v3/api-docs.yaml\" target=\"_blank\">📑 YAML OAS 3.0</a>\n"
      + "      <a href=\"/api/versions\" target=\"_blank\">🏷️ API Versions</a>\n"
      + "    </nav>\n"
      + "  </header>\n"
      + "  <main class=\"container\">\n"
      + "    <div class=\"hero-card\">\n"
      + "      <h1>Especificación de Contrato OpenAPI 3.0 y Versionamiento</h1>\n"
      + "      <p>Bienvenido al explorador de contratos OpenAPI de <strong>Taco Cloud</strong>. Esta plataforma cuenta con versionado formal por URI (<code>/api/v1</code> y <code>/api/v2</code>) y por cabecera HTTP <code>X-API-Version</code>.</p>\n"
      + "      <div class=\"version-selector\">\n"
      + "        <label for=\"specSelect\"><strong>Seleccionar Contrato:</strong></label>\n"
      + "        <select id=\"specSelect\" onchange=\"switchSpec(this.value)\">\n"
      + "          <option value=\"/v3/api-docs\">Contrato Unificado Completo (v1 + v2)</option>\n"
      + "          <option value=\"/v3/api-docs/v1\">Taco Cloud API v1 (Estable / Retrocompatible)</option>\n"
      + "          <option value=\"/v3/api-docs/v2\">Taco Cloud API v2 (Evolución con DTOs y HATEOAS)</option>\n"
      + "        </select>\n"
      + "        <a id=\"viewRawBtn\" class=\"btn\" href=\"/v3/api-docs\" target=\"_blank\">Ver JSON Raw</a>\n"
      + "        <a id=\"viewYamlBtn\" class=\"btn btn-secondary\" href=\"/v3/api-docs.yaml\" target=\"_blank\">Ver YAML Raw</a>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "\n"
      + "    <h2>Endpoints de la API Taco Cloud</h2>\n"
      + "\n"
      + "    <h3>Versión 2 (Recomendada / Evolved)</h3>\n"
      + "    <div class=\"endpoint-card\">\n"
      + "      <div class=\"endpoint-header\">\n"
      + "        <span class=\"method post\">POST</span>\n"
      + "        <span class=\"path\">/api/v2/orders</span>\n"
      + "        <span class=\"summary\">Crear orden estructurada con OrderV2Request y retorno OrderV2Response (Idempotency-Key support)</span>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "    <div class=\"endpoint-card\">\n"
      + "      <div class=\"endpoint-header\">\n"
      + "        <span class=\"method get\">GET</span>\n"
      + "        <span class=\"path\">/api/v2/orders/{id}</span>\n"
      + "        <span class=\"summary\">Consultar detalle enriquecido V2 con enlaces HATEOAS y tracking</span>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "\n"
      + "    <h3>Versión 1 (Estable / Canónica)</h3>\n"
      + "    <div class=\"endpoint-card\">\n"
      + "      <div class=\"endpoint-header\">\n"
      + "        <span class=\"method post\">POST</span>\n"
      + "        <span class=\"path\">/api/v1/orders</span>\n"
      + "        <span class=\"summary\">Crear orden canónica TacoOrder (alias /api/orders)</span>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "    <div class=\"endpoint-card\">\n"
      + "      <div class=\"endpoint-header\">\n"
      + "        <span class=\"method get\">GET</span>\n"
      + "        <span class=\"path\">/api/v1/orders</span>\n"
      + "        <span class=\"summary\">Historial de órdenes del usuario autenticado</span>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "    <div class=\"endpoint-card\">\n"
      + "      <div class=\"endpoint-header\">\n"
      + "        <span class=\"method get\">GET</span>\n"
      + "        <span class=\"path\">/api/v1/tacos</span>\n"
      + "        <span class=\"summary\">Catálogo de tacos recientes y recetas</span>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "    <div class=\"endpoint-card\">\n"
      + "      <div class=\"endpoint-header\">\n"
      + "        <span class=\"method get\">GET</span>\n"
      + "        <span class=\"path\">/api/v1/ingredients</span>\n"
      + "        <span class=\"summary\">Catálogo de ingredientes y disponibilidad</span>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "    <div class=\"endpoint-card\">\n"
      + "      <div class=\"endpoint-header\">\n"
      + "        <span class=\"method get\">GET</span>\n"
      + "        <span class=\"path\">/api/v1/announcements</span>\n"
      + "        <span class=\"summary\">Anuncios operativos seguros para cocina y reparto</span>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "    <div class=\"endpoint-card\">\n"
      + "      <div class=\"endpoint-header\">\n"
      + "        <span class=\"method get\">GET</span>\n"
      + "        <span class=\"path\">/api/versions</span>\n"
      + "        <span class=\"summary\">Ciclo de vida y metadatos de versiones soportadas</span>\n"
      + "      </div>\n"
      + "    </div>\n"
      + "  </main>\n"
      + "  <script>\n"
      + "    function switchSpec(url) {\n"
      + "      document.getElementById('viewRawBtn').href = url;\n"
      + "      document.getElementById('viewYamlBtn').href = url.endsWith('.yaml') ? url : url + '.yaml';\n"
      + "    }\n"
      + "  </script>\n"
      + "</body>\n"
      + "</html>";

  @GetMapping(path = {"/swagger-ui.html", "/swagger-ui/index.html", "/swagger-ui"}, produces = MediaType.TEXT_HTML_VALUE)
  @ResponseBody
  public Mono<String> swaggerUi() {
    return Mono.just(SWAGGER_HTML);
  }
}
